deployment:
  replicas: 1

service:
  type: NodePort
  nodePorts:
    http: 32080
    https: 32443

ports:
  web:
    port: 80
    nodePort: 32080
    exposePort: 32080

  websecure:
    port: 443
    nodePort: 32443
    exposePort: 32443

ingressRoute:
  dashboard:
    enabled: true
    insecure: true
    entryPoints:
      - web
    routes:
      - match: PathPrefix('/dashboard')
        kind: Rule
        services:
          - name: api@internal
            port: 80

providers:
  kubernetesIngress:
    enabled: true
    ingressClass: "traefik"  # This ensures that Traefik picks up Ingress resources annotated with "traefik"

securityContext:
  allowPrivilegeEscalation: true
  capabilities:
      drop:
      - ALL
      add:
      - NET_BIND_SERVICE

podSecurityContext:
  runAsNonRoot: false
  runAsUser: 0
  runAsGroup: 0

additionalArguments:
  - "--api.insecure=true"       # Enable the dashboard without authentication
  - "--api.dashboard=true"
  - "--entryPoints.web.address=:80"
  - "--entryPoints.web.http.http2.enabled=true"
  - "--entrypoints.websecure.address=:443"
  - "--providers.kubernetescrd.allowCrossNamespace=true"

resources: {}
persistence:
  enabled: false
